"name": "tryethereum"
"version": "0.0.1"
"description": "Ethereum testing server"
"dependencies": 
    "underscore": "*"
    "async": "*"
    "crypto": "*"
    "express": "*"
    "mongodb": "*"
    "bitcoinjs-lib": "https://github.com/bitfloor/bitcoinjs-lib/tarball/master"
    "wiredep": "*"
    "gulp": "*"
    "gulp-jade": "*"
    "gulp-stylus": "*"
    "gulp-coffee": "*"
    "gulp-flatten": "*"
    "gulp-rename": "*"
    "gulp-nodemon": "*"
    "gulp-util": "*"
    "gulp-angular-templatecache": "*"
    "brunch": "*"
    "jade": "~0.33"
    "coffee-script": "~1.6"
    "javascript-brunch": ">= 1.0 < 1.8"
    "coffee-script-brunch": ">= 1.0 < 1.8"
    "css-brunch": ">= 1.0 < 1.8"
    "less-brunch": ">= 1.0 < 1.8"
    "stylus-brunch": ">= 1.0 < 1.8"
    "auto-reload-brunch": ">= 1.0 < 1.8"
    "uglify-js-brunch": ">= 1.0 < 1.8"
    "clean-css-brunch": ">= 1.0 < 1.8"
    "jade-angularjs-brunch": "~0.0.5"
    "karma": "~0.9.4"
    "karma-coffee-preprocessor": "~0.0.2"
    "karma-ng-scenario": "~0.0.2"
