"name": "tryethereum"
"version": "0.0.1"
"description": "Ethereum testing server"
"dependencies": 
    "underscore": "*"
    "async": "*"
    "crypto": "*"
    "express": "*"
    "jade": "*"
    "mongodb": "*"
    "bitcoinjs-lib": "https://github.com/bitfloor/bitcoinjs-lib/tarball/master"
    "wiredep": "*"
    "gulp": "*"
    "gulp-jade": "*"
    "gulp-stylus": "*"
    "gulp-coffee": "*"
    "gulp-flatten": "*"
    "gulp-nodemon": "*"
    "gulp-util": "*"
